# Generated by Django 6.0.5 on 2026-05-28 06:00

import core.images.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to=core.images.paths.original_upload_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.images.paths.original_upload_path),
        ),
    ]
