# Generated by Django 6.0.5 on 2026-05-13 04:11

import tools.get_upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_create_by_alter_productimage_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=tools.get_upload_path.get_upload_path),
        ),
    ]
